### ISSUE TITLE
Convert event codes to other types

### ISSUE THREAD

**Issue by siikamiika** [ndesh26/evdev-rs#11]
I'm trying to read events from a device with `evdev-rs` and then feed the events to virtual uinput devices created with `rust-uinput`. When I try to cast the events to a format that can be understood by `rust-uinput`, I'm getting this error:
```
error[E0605]: non-primitive cast: `evdev_rs::enums::EventCode` as `u32`
  --> src/main.rs:51:33
   |
51 |                         e_code: e.1.event_code as u32,
   |                                 ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait
```
I'm very new to Rust and don't really know what to do to solve this, but if I understand it correctly, I need `impl From<evdev_rs::enums::EventCode> for u32` somewhere.

**Comment by siikamiika** [comment]
Okay I'm sorry, I missed `evdev_rs::util::event_code_to_int`. Reading it will be good homework for me. Thanks for the great lib!

**Comment by ndesh26** [comment]
Glad to know that lib is helping people!!
