### ISSUE TITLE
Proposal: Make enums CamelCase to match Rust style

### ISSUE THREAD

**Issue by acheronfail** [ndesh26/evdev-rs#17]
This might be controversial, however I’m proposing that we should match [Rust's guidelines](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html) and change the enums from `CONST_CASE` to `CamelCase`.

IMO it makes it easier to read and understand at a glance what's happening, since developers are used to enums being `CamelCase` when writing Rust.

It also removes the need for the `#[allow(non_camel_case_types)]` override.

---

I've already made the required changes in my branch here: https://github.com/ndesh26/evdev-rs/compare/master...acheronfail:chore/use-rust-convention-for-enum-names

**Comment by ndesh26** [comment]
Thanks for the patch. I am not so sure about this and I would like to think about this a bit more.

**Comment by ndesh26** [comment]
After thinking about it for a while, I think it will be better to leave event types as they as all the other enums follow the Rust guidelines. 

I want the event types to be the same across language and the same thing is done by `python-libevdev`. But in any case, I will leave this issue open and if more people prefer it to be `CamelCase` then we can make the change. 

Thanks for the patch as always!!

**Comment by acheronfail** [comment]
I'm happy to close this, since the more I use this crate the less important it is to me that the enums are `CamelCase` rather than `CONST_CASE`. It makes the relationship between the `C` libevdev library and this crate a little closer.

So, with that in mind I'm going to clone this issue. :)
