### ISSUE TITLE
Potentially incorrect types for some libevdev functions

### ISSUE THREAD

**Issue by acheronfail** [ndesh26/evdev-rs#20]
I'm not sure if this is machine specific, or hardware specific, but I've found that setting the device version which is currently a `libc::c_int` (`i32`) actually results in the version being truncated:

```rust
#[test]
fn device_get_version() {
    use std::i32;

    let d = Device::new().unwrap();
    d.set_version(i32::MAX);
    // This assertion fails!
    assert_eq!(d.version(), i32::MAX);
}
```

Doing some tests, it seems that the device version should actually be a `u16` (or `libc::c_ushort`).

The libevdev documentation just has `int` as the type: https://www.freedesktop.org/software/libevdev/doc/latest/group__bits.html#ga75a07d0c96dfe09d2194c104c429d0ae

**Comment by acheronfail** [comment]
Looking at the `evdev-sys/libevdev/libevdev/libevdev.h` file, it seems that `libevdev` also says it's an `int`:

```c

/**
 * @ingroup bits
 *
 * @param dev The evdev device, already initialized with libevdev_set_fd()
 *
 * @return The device's firmware version
 *
 * @note This function is signal-safe.
 */
int libevdev_get_id_version(const struct libevdev *dev);
```

**Comment by acheronfail** [comment]
I assume this is just a quirk of `libevdev`... In any case, it caught me out and I thought it might be useful to know.

I think we should honour the types provided by `libevdev`, but if this doesn't just happen on my machine it might be useful to add a doc comment somewhere in `evdev-rs` to inform any future users.

**Comment by ndesh26** [comment]
This looks interesting. I will try it on my system once I get home and report the findings here.

**Comment by ndesh26** [comment]
I am able to reproduce your observation. I was thinking of reporting this error in the libevdev community. They might be able to resolve/investigate it better.

**Comment by acheronfail** [comment]
For reference: https://lists.freedesktop.org/archives/input-tools/2019-March/001503.html

**Comment by acheronfail** [comment]
> The values are guaranteed to be a short though, simply by how libevdev wraps the kernel. So you can write the rust bindings to take a `uint16` instead and you'll be safe and have a better API at the same time.

So, IIUC we should update all the `c_int` types in `evdev_sys` to use `c_short` (or `u16` integer types instead?

**Comment by ndesh26** [comment]
I think it will be better to handle this conversion in evdev-rs. So that we still keep the one to one mapping that we have in evdev-sys. Let evdev-sys take in c_int as usual but evdev-rs accepts u16 in the api.  In any case I will merge this change a little late as this is a breaking change and will require a minor version bump.
