### ISSUE TITLE
enable_event_type is private

### ISSUE THREAD

**Issue by esjeon** [ndesh26/evdev-rs#21]
Hello,

I found that `enable_event_type` is currently private. I know that `enable` can do the job, but it's basically not upstream, and would confuse people. Also, I think its use of `&Any` unnecessarily risks type-safety.

I suggest:

1. Keep all of `enable`, `enable_*`, `disable`, and `disable_*` public.
2. Explicitly mention `enable` and `disable` in the documentation of `enable_*` and `disable_*`.

**Comment by ndesh26** [comment]
Hello,

Thanks for the suggestion.

I am open to making them public as I had done in case of enable_event_code. But in that case, it was due to a lack in the feature of rust API. My initial motivation for making them private was to force people to use the `enable` function to make the API more rustic. I felt that the rust API will be more easier for people to use.

Can you elaborate a bit on your motivation for making the functions public?

**Comment by esjeon** [comment]
> Can you elaborate a bit on your motivation for making the functions public?

My biggest complaint is the type-safety. I'm not really a fan of "safety" thingy, but `Any` is too much and not quite Rustic per-se, and better be avoided if possible. This combined with duplicated names (e.g. `EventType::EV_KEY` and `enum EV_KEY`) is a good source of confusion and error. However, I admit that if Rust improves its type system, this will be a clear winner, but not right now at least.

Also, I don't see any problem of having both interfaces. One is more rusty and concise, while the other is more upstream, type-safe, and verbose. They have different corners, I think. Having upstream-ish interface can also help migrations too. People will get confused if they can't immediately find any corresponding functions. Let's not surprise people unnecessarily.

Talking about "surprise", well, I'm actually quite pleasantly surprised with the enums. I like that I can combine event type and code in a type-safe way, which is impossible in C and many other languages. (C++ can, but not trivially.) Compared to this, `enable` isn't really a charming solution, and invalidates the whole point of the enums.

**Comment by ndesh26** [comment]
Fair enough. We can at least make both the interfaces public.
