### ISSUE TITLE
`Device::next_event` panics on unknown input code

### ISSUE THREAD

**Issue by esjeon** [ndesh26/evdev-rs#23]
Hello, again.

One of my mice is causing panic inside the library. It panics [right here](https://github.com/ndesh26/evdev-rs/blob/507aa1dd300fa472cc83066e9f1eceaf8885af3b/src/device.rs#L702), while converting a raw event code to `EventCode`. Basically, `None` returned from `int_to_event_code` is blindly `unwrap`-ed to panic.

The problem is that the mouse emits `REL_WHEEL_HI_RES`, which is defined in Linux header, but *not* in `libevdev/include/linux/input-event-codes.h`. 

A quick regeneration of `enums.rs` using Linux headers does the trick ([enums.rs.diff](https://github.com/ndesh26/evdev-rs/files/3490594/enums.rs.diff.txt)), but I don't recommend this because this isn't a permanent solution. The problem will recur whenever the kernel updates the list of codes. Also, I don't think it's okay to bypass the upstream, especially because the upstream [uses the local header to generate the list of names](https://github.com/whot/libevdev/blob/c3953e1bb8f813f3e248047d23fb0775b147da9f/libevdev/Makefile.am#L31). So it's better to keep away from the Linux headers.

My suggestion is to allow the explicit use of unknown event type/code values, which is probably the only future-proof solution. 

I've created [an experimental branch](https://github.com/esjeon/evdev-rs/tree/hack-enum-unknown) that adds `Unknown` variant to `EventCode`. Note that this is just an experiment for showcasing a possible solution, not quite something pull-able. This might look a little hacky, but this little change should be enough to postpone a major interface overhaul.

**Comment by ndesh26** [comment]
Thanks for bringing the problem to my notice!!

I need to think more on this issue. I am not yet sure about the best way to handle an unknown event type/code. One of the important factor that is affecting my decision is the fact that I recently merged a patch which is going to break the ABI and hence we are looking at a major version update anyways. So I'm open to accepting changes modifying the interface itself. 

I will have a look at your patches and see what can be done.

**Comment by ndesh26** [comment]
I'm not sure how I should deal with EN_UNK in EventType. Including the event_type with it breaks the ease of use of the EvenType enum at various places. I will ponder on it some more. Please let me know if you have some ideas.

**Comment by esjeon** [comment]
Yeah, that's where I exactly got stuck, too. I found that Rust enum isn't powerful enough to support this case.

Luckily, there's [a recently merged RFC](https://rust-lang.github.io/rfcs/2363-arbitrary-enum-discriminant.html) that allows assigning discriminants to struct-/tuple-like variants. [I've already got my hands on it](https://github.com/esjeon/evdev-rs/commit/087b7c28e959c0791efe73ff233118c2980d52fe). Using this, `EV_UNK` will be able to have both a discriminant and fields, but the current implementation doesn't support casting to integer. Ideally, we can request the direct casting as a new feature in the language, and keep all the goodies. (Plus, if this gets through, some `match`es can be removed for good.)

Still, this won't solve the problem in the short term, and it's unclear if things will work in our favor. So, I suggest quick patching this for now.

**Comment by tehwalris** [comment]
I'm having the same issue as @esjeon: When I use the scroll wheel of my mouse, `next_event` panics.

Unfortunately the fix in c82e7b3a53f3641cc893b84ad08aa4242f451089 is not sufficient to prevent a panic in my case. I get events with `event_type: 2, event_code: 11` (so a known `event_type`, but unknown `event_code`). This causes a panic at `int_to_event_code(ev.type_ as u32, ev.code as u32).unwrap()` in `next_event`. 

I will open a PR with my current fix so that you can give feedback.
