### ISSUE TITLE
Add serialization support

### ISSUE THREAD

**Issue by maxbla** [ndesh26/evdev-rs#35]
I would like to be able to serialize `InputEvent`s. If you derive `Serialize` and `Deserialize` on `InputEvent` (and all it's structure elements), I'll easily be able to do so. Serialization support should probably be hidden behind an off-by-default feature flag, since you don't want all users to pay for something only some need.

There might be some other structs that could benefit from serialization support, I haven't looked through them all. I could submit a PR for this issue if you'd like.

**Comment by ndesh26** [comment]
I'd be happy to accept it as long as it is not disrupting the flow for a normal user.
