### ISSUE TITLE
evdev-sys Build.rs breaks docs-rs

### ISSUE THREAD

**Issue by maxbla** [ndesh26/evdev-rs#36]
see log [here](https://docs.rs/crate/evdev-rs/0.4.0/builds/243661). The exact cause of the problem requires a little more digging, but [this](https://gitlab.freedesktop.org/libevdev/libevdev/-/blob/master/autogen.sh) script fails.

The docker image docs.rs uses does not include (the apt package) libevdev-dev, which contains headers necessary to use libevdev, so your script tries to build libevdev from source, which fails. Note that the docker image does contain (the apt package) libevdev2, which contains libevdev.so, but no headers. I think the proper fix here is to request docs.rs include libevdev-dev in their [packages.txt](https://github.com/rust-lang/crates-build-env/blob/master/packages.txt).

It's also a problem that the script downloading and compiling libevdev doesn't seem to work in the docs.rs environment, but I'm not convinced that building libevdev when it is not present is a good idea. I think doing so violates the least surprise principle.

**Comment by jyn514** [comment]
Both packages are rebuilt on docs.rs so I think this can be closed.

**Comment by maxbla** [comment]
I would still prefer that `build.rs` didn't try to download and compile libevdev when it isn't present.

**Comment by ndesh26** [comment]
Thanks @maxbla for resolving the issue. All the other rust bindings build the library in case it is absent and I would like to keep it consistent with them. 

I will add a warning in the current code to indicate that we are building libevdev ourselves so that the user is not caught by surprise.

**Comment by jyn514** [comment]
> All the other rust bindings build the library in case it is absent

FWIW, this is not true of any of the bindings maintained by core team members AFAIK. See for example [git2](https://docs.rs/crate/libgit2-sys/0.12.7+1.0.0/source/build.rs) and [openssl](https://docs.rs/crate/openssl-sys/0.9.58/source/build/main.rs), both of which require that pkg-config return an already installed library. Openssl does have a `feature` to compile a vendored version from source, but it never downloads anything from the internet.

Personally, I would also find downloading things surprising.

**Comment by maxbla** [comment]
Openssl has a `#[cfg(feature = "vendored")]` around using `openssl-src`, which is a crate that builds openssl from source, as the name suggests. The key point there is that vendored openssl is a feature, and is **disabled by default**. I think a similar approach could work well here.

**Comment by maxbla** [comment]
`build.rs` failed on crates.rs before crates.rs added libevdev-dev. That indicates a bug, although I can't reproduce it (outside the build.rs docker image), and don't fully understand why it happened.

**Comment by jyn514** [comment]
> build.rs failed on crates.rs before crates.rs added libevdev-dev

docs.rs disables network access and writing to the source directory. So not a bug, but a pretty good indication that something is fishy.

**Comment by maxbla** [comment]
Oh. Duh. The log indicates it failed on the line
``` rust
cmd.env("CC", compiler.path())
       .env("CFLAGS", cflags)
       .current_dir(&dst.join("build"))
       .arg(src.join("libevdev/autogen.sh").to_str().unwrap()
               .replace("C:\\", "/c/")
               .replace("\\", "/"));
```
But that line failed because earlier,
``` rust
let _ = Command::new("git").args(&["submodule", "update", "--init"])
                           .status();
```
never checked that status was `success()`, but the download failed.

**Comment by ndesh26** [comment]
> See for example [git2](https://docs.rs/crate/libgit2-sys/0.12.7+1.0.0/source/build.rs) and [openssl](https://docs.rs/crate/openssl-sys/0.9.58/source/build/main.rs), both of which require that pkg-config return an already installed library. 

I was aiming for the same thing done in git2 bindings. They indeed download and build git2 in case it is not available in the system. The case for openssl might be different as it comes preinstalled with the distros.

**Comment by ndesh26** [comment]
> never checked that status was `success()`, but the download failed.

Good point. I should check the status of this operation.

**Comment by maxbla** [comment]
I'm willing to close this, as the ecosystem as a whole seems to use build scripts the way this crate does, and I refactored it a bit in #40, so every command is checked for success.
