### ISSUE TITLE
Impl `TryInto<SystemTime>` for `TimeVal`

### ISSUE THREAD

**Issue by maxbla** [ndesh26/evdev-rs#41]
It is possible to convert `TimeVal` into `SystemTime` easily, but this libaray provides no method for the reverse. Implementing `TryInto<SystemTime>` will fix this, and should be fairly simple, something like:
```rust
impl TryInto<SystemTime> for TimeVal {
    type Error = ();
    fn try_into(self) -> Result<SystemTime, Self::Error> {
        UNIX_EPOCH.checked_add(std::time::Duration::new(self.tv_sec, self.tv_usec*1000)).ok_or(Err(()));
    }
}
```

**Comment by ndesh26** [comment]
Thanks for raising this issue!!
