### ISSUE TITLE
Run rustfmt and add formatting check to CI

### ISSUE THREAD

**Issue by maxbla** [ndesh26/evdev-rs#43]
It is nice when making changes to be able to autoformat my changes, but doing so changes formatting all over the place. Ensuring all files are formatted seems like a reasonable way to fix this.

**Comment by ndesh26** [comment]
Yes I agree. We need to have a initial commit which does all the formatting change and then we can include format change in the CI check.

**Comment by maxbla** [comment]
Cool. I can set that up, but there will be merge conflicts if we do it before #40.

**Comment by ndesh26** [comment]
Better to do it after #40. You can either base your changes on #40 or wait until I merge it.
