### ISSUE TITLE
Add rust bindings to libevdev readme

### ISSUE THREAD

**Issue by maxbla** [ndesh26/evdev-rs#49]
The libevdev [readme](https://gitlab.freedesktop.org/libevdev/libevdev/-/blob/master/README.md) lists bindings. We should get evdev-rs on that list.

See also:
[similar issue on libevdev gitlab](https://gitlab.freedesktop.org/libevdev/libevdev/-/issues/14)
[merge request adding haskell bindings](https://gitlab.freedesktop.org/libevdev/libevdev/-/merge_requests/56/diffs)

**Comment by ndesh26** [comment]
Sure! Thanks for noticing it! Should I create a pull request or would you like to do that?

**Comment by maxbla** [comment]
I think it makes sense for you to do so. I was planning on doing it only if you took a while to respond or were not interested.

**Comment by ndesh26** [comment]
I will take care of it then! Thanks.

**Comment by ndesh26** [comment]
Merged in the libevdev.
