### ISSUE TITLE
Creating a UInputDevice with all events enabled

### ISSUE THREAD

**Issue by georgefst** [ndesh26/evdev-rs#50]
I'm creating a tool for sharing keyboards over a local network. Thus I need to be able to enable all keys on the virtual device.

One option is a few hundred lines of:
```rust
dev.enable(&EventCode::EV_KEY(EV_KEY::KEY_0)).unwrap();
dev.enable(&EventCode::EV_KEY(EV_KEY::KEY_1)).unwrap();
...
```

Instead I've ended up forking this library, adding derived implementations of `EnumIter` from [strum](https://crates.io/crates/strum), and using:
```rust
for key in EV_KEY::iter() {
    dev.enable(&EventCode::EV_KEY(key)).unwrap();
}
```

Would you accept a PR adding these instances, or would you not consider it worth incurring the dependency? Is there a better way (I'm pretty new to Rust)?

Incidentally, is there a particular reason the docs encourage the use of `enable` over `enable_event_code`? It seems like it's trading type-safety for saving a few characters.

**Comment by ndesh26** [comment]
We already have an implementation of the iterator interface for EventCode. Please check `examples/evtest.rs` for an example, specifically the functions `print_bits` and `print_code_bits`. 

The major reason for encouraging the use of `enable` was to have an easier API. Yes, it could lead to type safety errors. I recently had a discussion to implement `enable` using traits which will give us both the benefits. It will be updated soon.

**Comment by georgefst** [comment]
> We already have an implementation of the iterator interface for EventCode.

Ok, I have been able to implement this using that interface. It feels a bit lower-level than the rest of this library since I'm required to actually know about the numeric values of events, in this case knowing that `EV_KEY::KEY_RESERVED` is the "minimum" key event, and that the key events form a single contiguous subsequence of the full sequence of events.

**Comment by ndesh26** [comment]
Now that I think about it the interface is somewhat lower level than I would like. However I would like to handle it by adding the iterator code (using traits) rather than using a external trait.  

I will introduce the iterator interface to handle it.

**Comment by ndesh26** [comment]
Sorry for the late reply. After thinking over it more I think it is best to use strum for this use case. I would prefer to avoid an extra dependency but there is no way to clean way to deal around this problem. 

Can you create a PR for this change?

**Comment by georgefst** [comment]
> Can you create a PR for this change?

I could. But it's pretty low-priority for me now since I've finished the project that I was using this library for.

**Comment by ndesh26** [comment]
Ah..Okay. I will create a PR myself. I wanted to include this change for the next release.

**Comment by maxbla** [comment]
Strum is unnecessary for this use case. You already wrote the code for iterators, now all you need is some user-friendly method to create a EventTypeIterator that starts at 0 (EventType::EV_SYN) and the same for EventCodeIterator and InputPropIterator. For example
```rust
impl EventTypeIterator {
    /// Creates a new `EventTypeIterator` that iterates over all `EventType`s
    pub fn new() -> Self {
        EventTypeIterator{current: EventType::EV_SYN}
    }
}
```

Also I agree that `DeviceWrapper::enable` in it's current state is not very rusty.

**Comment by ndesh26** [comment]
I am trying to solve this, but one major problem that I am facing is that `EventCodeIterator` goes over all the `EventCodes` and not just the `EventCode`s corresponding to a particular `EventType`. I assume that it is more likely that a user would want toonly enable a set of `EventCode`s related to `EventType`. But to have that kind of API, we would have to let go of the ability to iterate over all `EventCode`s in a single loop.
