### ISSUE TITLE
FromStr for core types

### ISSUE THREAD

**Issue by georgefst** [ndesh26/evdev-rs#51]
One of my use cases for this library would benefit from an `impl FromStr for EV_KEY` (to set a key from a command line argument, using the "clap" library). Implementations for this and various other types could be implemented by binding the relevant [libevdev helper functions](https://www.freedesktop.org/software/libevdev/doc/latest/group__misc.html). Alternatively, they could just be generated as part of a script like `make-event-names.py`.

I'd be able to put up a PR for this.

**Comment by ndesh26** [comment]
I would be happy to have this change!

**Comment by georgefst** [comment]
Actually, there are at least two more ways of doing this:
- Piggyback on `serde` - use e.g. `serde_json` and fail if the input doesn't correspond to a JSON string.
- Use [strum](https://docs.rs/strum_macros/0.19.3/strum_macros/derive.EnumString.html). This would be my preferred approach. It would require very little code, the dependency is very small, and it would also help with #50.

Which would you prefer?
