### ISSUE TITLE
Why the EventCode didn't implement Copy trait?

### ISSUE THREAD

**Issue by lj94093** [ndesh26/evdev-rs#58]
The EventCode is just some int,it's not expensive for it to implement the Copy trait.

**Comment by maxbla** [comment]
In the master branch, `EventCode` does implement `Copy`. This was added in 0ba5d6450dbf4e4dec3c1b4745525172f6805769. For now, you can add `evdev-rs = {git="https://github.com/ndesh26/evdev-rs.git"}` to cargo.toml. @ndesh26 We should probably publish a new release.

**Comment by ndesh26** [comment]
@lj94093 Please use the method mentioned by @maxbla if you need this feature urgently. 

@maxbla Life has been hectic for the past couple of months. I wanted to fix a few things in the function signatures before I release v5.0.  This release has a lot of changes to the functions which are vital to the most basic usage of the library. Hence it is going to break most people's workflow. Hence I wanted to ensure that I account for all the future scenarios before making the release. 

I will try to get it done over the weekend.

**Comment by maxbla** [comment]
I'm sorry to hear that life has been hectic. What were you thinking related to function signatures? I would be happy to help. Also this is a tad off topic - it would make sense to close this issue and discuss in another issue.

**Comment by ndesh26** [comment]
Closing this issue. I will create relevant pull requests.
