### ISSUE TITLE
Open files with O_NONBLOCK

### ISSUE THREAD

**Issue by maxbla** [ndesh26/evdev-rs#59]
The documentation of libevdev states
```
* libevdev does not handle the file descriptors directly, it merely uses
* them. The caller is responsible for opening the file descriptors, setting
* them to `O_NONBLOCK` and handling permissions. A caller should drain any
* events pending on the file descriptor before passing it to libevdev.
 ```
(this is in `libevdev.h`)

Rust's `File::open` does not set `O_NONBLOCK` (it uses `O_RDONLY|O_CLOEXEC`). I'm not sure what problems this could cause.

~One way to fix this is to add a pub fn called `Device::open_from_path()`, which calls into libc directly.~ See comment below for code that uses only safe rust
<details>
<summary> unsafe example code (do not use) </summary>
 
```rust
pub fn open_from_path<P>(path: P) -> io::Result<Device>
where P: AsRef<OsStr>
{
    let path = CString::new(path.as_ref().as_bytes()).unwrap();
    let fd = match unsafe {
        libc::open(path.into_raw(), libc::O_RDONLY | libc::O_NONBLOCK | O_CLOEXEC)
    } {
        -1 => return Err(io::Error::last_os_error()),
        res => res
    };
    // maybe drain events here?
    Device::new_from_file(unsafe{File::from_raw_fd(fd)}))
}
```
</details>
(note: a way to improve this function is to use `fd`s directly to create a Device instead of rust `File`s)

Before we do this, I think we should investigate what if any bugs result from not opening with O_NONBLOCK

**Comment by maxbla** [comment]
I propose adding a method to device called something like `fn<P: AsRef<Path>> new_from_path(path:P) -> io::Result<Device>` where the implementation opens a file (using libc::open/openat) that has O_NONBLOCK enabled, then deprecating `Device::new_from_file`. Alternatively, whenever a file is passed in, this library could set O_NONBLOCK on it with `fcntl(fd, F_SETFL, O_NONBLOCK)`, silently diverging from how libevdev does things.

**Comment by maxbla** [comment]
using `libc::open` as suggested in the top-level comment is a bad idea. A better way to do it (no unsafe) is
```rust
use std::os::unix::fs::OpenOptionsExt;
// ...
// Open a file with O_NONBLOCK
let mut file = OpenOptions::new()
    .read(true)
    .write(true)
    .custom_flags(libc::O_NONBLOCK)
    .open(path)
```

**Comment by ndesh26** [comment]
I added a new method as creating a device from path as you suggested. However I'm not in favor of deprecating new_from_file as the user might wanna handle opening the file himself.

**Comment by maxbla** [comment]
If we don't deprecate `new_from_file` we need to at least learn what problems can happen when not opening with `O_NONBLOCK` by either reading source code of libevdev or by asking its authors. I think its just a deadlock, but might be undefined behavior. If the answer is undefined behavior `new_from_file` must be marked unsafe. I think our docs should say something like "prefer using `new_from_path` if evdev library code is the only thing you expect to read from or write to the device file" and the examples and tests should be changed to use `new_from_path` almost everywhere.

Also that PR does not address "A caller should drain any events pending on the file descriptor before passing it to libevdev". Its pretty easy to just read off the file until it would block, so we could try that.

**Comment by ndesh26** [comment]
Let's confirm with the libevdev authors about the behaviour when the file is used without `O_NONBLOCK`. We can deal with it based on their reply. 

I had updated the main example in our code to use new_from_path function instead. But left the call to new_from_file in `evtest.rs` as I wanted to leave an example of how the file should be properly opened. If you feel strongly about recommending new_from_path then I can shift the example file opening code as a comment in new_from_file and use new_from_path everywhere.

I will update my PR to handle the draining of events from file.

**Comment by ndesh26** [comment]
I got the following reply from Peter (maintainer of libevdev): 

> > Hello,
> >
> > The libevdev requires that the fd should be opened with the O_NONBLOCK
> > flag. What kind of behaviour can we expect if we try to create a
> > libevdev device without the O_NONBLOCK flag? The main question is
> > whether it will be blocked or it could be undefined behaviour as well.
> >
> > A little background, I have written libevdev bindings in rust [1] and
> > I wanted to document the kind of behaviour people should expect and
> > whether I should mark the function as unsafe if it were to exhibit
> > undefined behaviour.
>
> no worries there, it's well-defined behaviour, but you should use the
> LIBEVDEV_READ_FLAG_BLOCKING  flag in libevdev_next_event(). Reason being
> that libevdev tries to read more events from the fd to cache them whenever
> you call that function [1], which means if the fd may block even when more
> events are already cached and ready to be returned. With that flag you
> disable that part, so reading only blocks when there are no more events
> cached and we really need to read from the fd.
>
> IOW, the code is (very) roughly like this:
>
>         def libevdev_next_event(self, flags):
>            if self.queue.is_empty() || flags != READ_FLAG_BLOCKING:
>                    self.queue.append_events_from_fd()
>
>            return self.queue.pop(0)
>
> Cheers,
>    Peter
>
> [1] goal is to avoid SYN_DROPPED even when processing of any specific event
> takes a bit longer

**Comment by ndesh26** [comment]
I have added a comment to reflect the necessary use of ReadFlag::BLOCKING when file is opened without O_NONBLOCK. Please take a look at my PR and let if know if you have any more suggestions.
