### ISSUE TITLE
Nightly build fails due to absence of rust-fmt

### ISSUE THREAD

**Issue by ndesh26** [ndesh26/evdev-rs#63]
[0K$ rustup component add rustfmt
error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly
Sometimes not all components are available in any given nightly. If you don't need the component, you can remove it with:

    rustup component remove --toolchain nightly --target x86_64-unknown-linux-gnu rustfmt
travis_time:end:01306cf8:start=1617507966988173204,finish=1617507967126668416,duration=138495212,event=before_script
[0K[31;1mThe command "rustup component add rustfmt" failed and exited with 1 during .[0m

Your build has been stopped.

**Comment by maxbla** [comment]
Missing components is a common problem with nightly. Best practice is CI should still report success even if nightly fails. It seems that Travis is already configured that way.

https://github.com/ndesh26/evdev-rs/blob/a02ad0dbda3384ecedd0f2ed57fdc657f055a056/.travis.yml#L31-L32

I don't think this is an issue with evdev-rs, really it is an issue with the rust compiler/components

**Comment by ndesh26** [comment]
Seems like the issue has been updated in rust-nightly. It is passing the build now.
