### ISSUE TITLE
Migrate to a new CI

### ISSUE THREAD

**Issue by ndesh26** [ndesh26/evdev-rs#73]
With the [updated terms](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) of Travis CI, public repositories can no longer run using a free plan. Each user is allotted an initial amount of 10000 credits and for more credits, for open-source projects, a mail needs to be manually sent to the Travis CI and they will allot some more credits on a case to case basis.

In my opinion, it is a hassle to move manually send a mail every time we run out of credits. I want to shift to other alternatives which offer free service to open source projects.

**Comment by maxbla** [comment]
The services I can think of are Github actions, Circle CI, Jenkins and Gitlab CI. Of those, all but Jenkins offer free services to open source projects. Gitlab CI obviously requires using Gitlab in some capacity.

I think github actions is a pretty good choice, although it represents vendor lock-in. I don't imagine the CI for this repository ever growing so much that switching to a new provider would be intractable, so I'm not too concerned. In addition, we might consider using [bors](https://github.com/bors-ng/bors-ng), as it solves a few problems for bigger projects like rust itself (namely absolutely never committing to master if a build fails).
