### ISSUE TITLE
How to convert key names to EventCode?

### ISSUE THREAD

**Issue by t184256** [ndesh26/evdev-rs#8]
How to convert key names to `EventCode`? I currently use deprecated `libevdev_event_code_from_name` from deprecated `libevdev_sys`. Or is this out of the scope of this library?

**Comment by ndesh26** [comment]
You can use the `from_str` function to get EventCode from key names.

```
let p = EventCode::from_str(EventType::EV_KEY, str).unwrap();
``` 

`libevdev_event_code_from_name` is not deprecated, you can use it freely. `libevdev_sys` is the library which exposes raw c functions from the libevdev library. `evdev-rs` acts as a wrapper around the raw c functions and exposes a rust-like API for the programmer. Ideally, you should avoid using c functions in your code directly.

**Comment by t184256** [comment]
OK, I have no idea how I missed this one. It also handles the invalid names properly. Sorry for the noise.
