### ISSUE TITLE
pkg_config::find_library probes an unexpected -L to system folder

### ISSUE THREAD

**Issue by rofferom** [ndesh26/evdev-rs#85]
# Problem description

This crate has some side effect to my project build. I'm actually working on a project that links to a `.so` that is installed in a custom path, using pkg-config to get the correct `-I`/`-L`/`-l` flags.

But when I'm linking to `evdev-rs`, I get an extra `-L/usr/lib/x86_64-linux-gnu` before my own `-L` flag. In my specific case, I want to link to a new version of a library that is already available in standard installation paths. Because of the wrong `-L` order, the linker will try to use the wrong library version (and fails to link because I'm adding some new symbols).

It would be better to get rid of this `-L/usr/lib/x86_64-linux-gnu`, and let the linker search into my `cargo:rustc-link-search` at first, and then fallback to `/usr/lib/x86_64-linux-gnu` that is a standard research path.

Maybe there is a way to force the `-L` order, but I haven't found it.

# Analysis

In `build.rs`, the call to pkg-config has a weird behavior.

I expected the flags to be configured like this:
```$ pkg-config --cflags --libs libevdev
-I/usr/include/libevdev-1.0/ -levdev
```

Instead, it does something else instead:
```
$ PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 pkg-config --cflags --libs libevdev
-I/usr/include/libevdev-1.0/ -L/usr/lib/x86_64-linux-gnu -levdev
```

Someone has already complained long ago about this, but the default behavior hasn't been changed: https://github.com/rust-lang/pkg-config-rs/pull/35. Instead, a configuration flag has been added to disable this behavior: https://github.com/rust-lang/pkg-config-rs/commit/d184e48619c0fe223ab7d11618ce7cae2e1d6811.

I made a test on my side with a `print_system_libs(false)`, and it fixes my build issue.

Do you think it is possible to change this behavior in `evdev-rs` ?

**Comment by ndesh26** [comment]
Yes I'd happy to accept a patch to fix this behavior.
