### ISSUE TITLE
evdev-sys as a dependency rebuilds on every compile

### ISSUE THREAD

**Issue by waynr** [ndesh26/evdev-rs#88]
Not sure why I wasn't seeing this a few days ago, but it just came to my attention tonight that `evdev-sys` compilation doesn't seem to hit the cargo/rustc cache (not sure what component of the toolchain actually caches builds).

When I run `cargo build -Z timings` this is what I see:

```
zsh/3 3140  (git)-[main]-% cargo build -Z timings
   Compiling evdev-sys v0.2.4
   Completed evdev-sys v0.2.4 build script (run) in 10.2s
   Compiling evdev-rs v0.4.0
   Completed evdev-sys v0.2.4 in 0.1s
   Compiling quantum-soft-keyboard v0.1.0 (/home/wayne/projects/qsk)
   Completed evdev-rs v0.4.0 in 0.6s
   Completed quantum-soft-keyboard v0.1.0 in 0.3s
   Completed quantum-soft-keyboard v0.1.0 bin "qsk" in 1.6s
```
This is immediately following a previous `cargo build`. 

This is making my editor workflow practically unusable -- the editor itself isn't blocking, but I run `watchexec` to either build or test after saving changes but because `rust-analyzer` and `cargo` are sharing a common build directory and the access to this build directory is mutually exclusive between the two, my `cargo build` (or `cargo test`) output has to delay the 10~ seconds `rust-analyzer` takes to build/check then the 10~ seconds `cargo build/test` takes so I have to wait at least 20 seconds to get a set of readable compiler errors/suggestions. 

I realize it's possible to tell `rust-analyzer` to use its own build directory, but even having to wait 10 seconds is disruptive for flow.

Anyone working on this project able to point me in the right direction of preventing this kind of rebuild? Or is it just always going to happen because of the fact that `evdev-sys` has a build script? Thanks in advance for any advice or insight you might be able to provide!

**Comment by ndesh26** [comment]
I don't know much about the caching part. I haven't heard about such a problem. Let me try to replicate it locally, then I can try to analyze it more. Meanwhile you can try linking with libevdev installed on your system. That might fix the rebuilds.

**Comment by ndesh26** [comment]
I was able to replicate it. It's not something specific to evdev though, I saw similar behaviour with other libraries as well. 
```
   Compiling lzma-sys v0.1.17 (/home/ndesh/xz2-rs/lzma-sys)
   Completed libc v0.2.69 in 1.2s
   Completed lzma-sys v0.1.17 build script in 0.7s
   Completed lzma-sys v0.1.17 build script (run) in 5.9s
   Compiling xz2 v0.1.6 (/home/ndesh/xz2-rs)
   Completed lzma-sys v0.1.17 in 0.2s
   Completed xz2 v0.1.6 in 0.4s
```
I haven't found the cause of the problem yet. The build script could be a likely culprit.

**Comment by waynr** [comment]
@ndesh26 thanks for taking a look at this! I've submitted #89 with a proposed fix -- any reason not to merge that soon? I'd like to stop pointing at my PR branch. Happy to further discuss any changes necessary on the PR.

**Comment by ndesh26** [comment]
> @ndesh26 thanks for taking a look at this! I've submitted #89 with a proposed fix -- any reason not to merge that soon? I'd like to stop pointing at my PR branch. Happy to further discuss any changes necessary on the PR.

Sorry for the delay, I'll review it tomorrow!

**Comment by ndesh26** [comment]
If your original problem is fully resolved with your patch then we can close this issue.

**Comment by waynr** [comment]
Thanks for reviewing and merging! The patch does indeed fix this problem, so I'll close the issue.
