### ISSUE TITLE
evdev_rs::util::int_to_event_code panics at invalid keycodes

### ISSUE THREAD

**Issue by t184256** [ndesh26/evdev-rs#9]
I currently use this frankenstein to convert key names to EventCodes, and it works, but only for valid keycodes.

```
fn key_code_from_name(s: String) -> Option<EventCode> {
    let type_as_uint = evdev_rs::enums::EventType::EV_KEY as c_uint;
    let code_name = CString::new(s).unwrap();
    let code_as_uint = unsafe {
        libevdev_sys::evdev::libevdev_event_code_from_name(
            type_as_uint, code_name.as_ptr()
        ) as c_uint
    };
    evdev_rs::util::int_to_event_code(type_as_uint, code_as_uint)
}
```

I believe that a panicky evdev_rs::util::int_to_event_code is to blame, specifically
```
EventType::EV_KEY => ev_code = EventCode::EV_KEY(int_to_ev_key(event_code as u32).unwrap()),
```

Shouldn't it just return None instead of panicking?

Sorry if I misunderstand something, as it is my first program in Rust.

**Comment by ndesh26** [comment]
Yes, you are correct. My bad I didn't handle the exception case properly. I will attach a patch to fix this.

Thanks for raising the issue.

**Comment by t184256** [comment]
Thanks for pointing at EventCode::from_str, which not only does exactly what I was trying to accomplish, but also handles invalid names properly.

**Comment by ndesh26** [comment]
Yes `EventCode::from_str` handles the invalid name property but `int_to_event_code` should also return None in that case
